name: CI

on:
  push:
    branches: [ master, v2 ]
  pull_request:
    branches: [ master, v2 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - uses: actions/checkout@v2
      - run: go build -v ./...
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - uses: actions/checkout@v2
      - run: go test -v ./...
  
  check:
    name: check file quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - uses: actions/checkout@v2
      - run: go vet -v ./...
      - run: gofmt -s -d -l .
